### ISSUE TITLE
大佬，请问一下为什么导出的onnx模型有两个输出呢？

### ISSUE THREAD

**Issue by leayz-888** [spacewalk01/tensorrt-yolov9#2]
![Screenshot from 2024-02-26 17-31-41](https://github.com/spacewalk01/tensorrt-yolov9/assets/51729318/d5a60ad4-7456-4dcf-8290-54ef3ad15a3c)

**Comment by spacewalk01** [comment]
The first one is prediction. I think the second one is loss output:
https://github.com/WongKinYiu/yolov9/blob/60a611741035d004d36fdd5c192817c8872bba1c/utils/general.py#L902
