### ISSUE TITLE
About trt inference

### ISSUE THREAD

**Issue by leayz-888** [spacewalk01/tensorrt-yolov9#3]
The author of yolov9 has updated the re-parameterization code. Before converting to onnx, you can re-parameterize it first, and then modify the output to only one, which can greatly shorten the inference time.

**Comment by spacewalk01** [comment]
I will look into your suggestion. Thank you :)

**Comment by spacewalk01** [comment]
It indeed reduces the number of parameters. I will apply it and update this repo. Thanks again.

**Comment by spacewalk01** [comment]
Applied re-parameterization!

**Comment by leayz-888** [comment]
> Applied re-parameterization!

nice! By the way, when I exported the onnx model, I only kept the final output. The generated engien file had fewer parameters. According to actual measurements, it can speed up by about 25%.

**Comment by leayz-888** [comment]
like this:
![Screenshot from 2024-02-27 15-26-47](https://github.com/spacewalk01/tensorrt-yolov9/assets/51729318/c5a6f978-d614-42c6-a50a-e380cf7091d9)

**Comment by spacewalk01** [comment]
Nice!

**Comment by leayz-888** [comment]
like this:
![Screenshot from 2024-02-27 15-30-24](https://github.com/spacewalk01/tensorrt-yolov9/assets/51729318/39263b5d-6653-462d-aa4c-bd7c000ff608)

**Comment by spacewalk01** [comment]
Indeed, I got the same result. Nice work!
