### ISSUE TITLE
No module named 'models'

### ISSUE THREAD

**Issue by Egorundel** [spacewalk01/tensorrt-yolov9#5]
Hello!
What should I do if this error pops up?

```
File "reparameterize.py", line 3 in <module>
    from models.yolo import Model
ModuleNotFoundError: No module named 'models'
```

![Screenshot from 2024-02-28 10-15-02](https://github.com/spacewalk01/TensorRT-YOLOv9/assets/65890558/4d706590-0d51-43ee-b268-fbe9777b38c0)

**Comment by spacewalk01** [comment]
You need to install yolov9 requirements first
