### ISSUE TITLE
Customize with data 3 classes

### ISSUE THREAD

**Issue by ThanhPham1987** [spacewalk01/tensorrt-yolov9#6]
Hi @spacewalk01 ,
I build model with 3 classes and convert to .engine. After converted to engine. I changed like this:

const vector<string> coconame = {
    "class 1",         "class 2",    "class 3",
    };

and changed  int out_rows = 84;--> int out_rows = 7
in yolov9.cpp file. 

I am facing problem:

terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(4.8.0) /home/velox/opencv/modules/core/src/matrix.cpp:766: error: (-215:Assertion failed) 0 <= _rowRange.start && _rowRange.start <= _rowRange.end && _rowRange.end <= m.rows in function 'Mat'

Aborted (core dumped)

Do you know how to solve?
PeterPham

**Comment by spacewalk01** [comment]
Hi @ThanhPham1987 Will you make sure your onnx model output is like [1, 7, 8400] 
![image](https://github.com/spacewalk01/TensorRT-YOLOv9/assets/6389915/0d2ef4d9-a396-426b-a8d9-ce06bfb1388f)

**Comment by ThanhPham1987** [comment]
![Screenshot from 2024-03-04 16-35-35](https://github.com/spacewalk01/TensorRT-YOLOv9/assets/22832922/e4b9ede4-9719-455a-ae3e-1b328094bc19)
Hi @spacewalk01 . yes, 1, 7, 8400. My output like this
![Screenshot from 2024-03-04 16-33-15](https://github.com/spacewalk01/TensorRT-YOLOv9/assets/22832922/6156507a-0a6b-4534-9a84-0df670bbff2c)

**Comment by spacewalk01** [comment]
You are modifying following code right:?
```
    int out_rows = 84;
    int out_cols = 8400;
    const cv::Mat det_output(out_rows, out_cols, CV_32F, (float*)mCpuBuffers[1]);

    for (int i = 0; i < det_output.cols; ++i) {
        const cv::Mat classes_scores = det_output.col(i).rowRange(4, 84);
```

**Comment by spacewalk01** [comment]
Please change like following
```
const cv::Mat classes_scores = det_output.col(i).rowRange(4, 84); ->

const cv::Mat classes_scores = det_output.col(i).rowRange(4, 7);
```

**Comment by ThanhPham1987** [comment]
Thanks
