### ISSUE TITLE
 'DetectionModel' object has no attribute 'nc' when reparametrize.py is performed

### ISSUE THREAD

**Issue by berkgungor** [spacewalk01/tensorrt-yolov9#8]
I finetuned the gelan-c.pt model and tried to reparametrize my custom model but i got this error : `yolov9\reparameterize.py", line 14, in main
    model.nc = ckpt['model'].nc
               ^^^^^^^^^^^^^^^^
  File "C:\Users\anaconda3\envs\torch\Lib\site-packages\torch\nn\modules\module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'DetectionModel' object has no attribute 'nc'`

( i modified the model parameters in reparameterize.py based on my custom configs, but did not change anything)

**Comment by spacewalk01** [comment]
https://github.com/WongKinYiu/yolov9/issues/131

**Comment by berkgungor** [comment]
reparameterize.py throws the same error when i try to run it on yolov9 weights too. anyway I'm closing here. owner of the repo noted that reparameterize.py is under construction currently.
