### ISSUE TITLE
YOLO V9 Seg support

### ISSUE THREAD

**Issue by toystorynova** [spacewalk01/tensorrt-yolov9#9]
Seems segmentation was added? Would you be able to add it here? Would be more than appreciated, thanks!

**Comment by spacewalk01** [comment]
Hi it seems there is a bug in segmentation code: https://github.com/WongKinYiu/yolov9/issues/233
I will try to work on it as soon as bug is fixed. Thanks for asking.

**Comment by spacewalk01** [comment]
Implemented yolov9 pan/instance segmentation using onnx python:
https://github.com/spacewalk01/yolov9-onnx-segmentation

**Comment by spacewalk01** [comment]
I will try to extend it.

**Comment by toystorynova** [comment]
Was hoping for a C++ TensorRT example, is that possible? or is that bug you linked stopping you from that? Nevertheless, appreciate your work!

**Comment by spacewalk01** [comment]
Yes i am very interested in working on c++ yolov9 segmentation using trt. Currently i am busy. I will try to work on it as soon as possible.

**Comment by spacewalk01** [comment]
Thanks for asking
